[oobe]
command = /etc/oobe.sh
defaultUid = 1000
defaultName = deepin

[shortcut]
enabled = true
icon = /usr/lib/wsl/deepin.ico

[windowsterminal]
enabled = true
ProfileTemplate = /usr/lib/wsl/terminal-profile.json
